# Generated by Django 5.0.14 on 2026-09-26 15:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='Verified', max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HospitalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='Swarnabindu Government Hospital', max_length=255)),
                ('nepali_hospital_name', models.CharField(default='स्वर्णविन्दु सरकारी अस्पताल', max_length=255)),
                ('address', models.CharField(default='Ward No. 4, Hospital Road', max_length=255)),
                ('district', models.CharField(default='Kavrepalanchok', max_length=100)),
                ('municipality', models.CharField(default='Panauti Municipality', max_length=100)),
                ('ward', models.CharField(default='04', max_length=20)),
                ('province', models.CharField(default='Bagmati Province', max_length=100)),
                ('phone', models.CharField(default='+977-01-5500000', max_length=50)),
                ('email', models.EmailField(default='info@swarnabindu.gov.np', max_length=254)),
                ('report_header', models.TextField(default='Government of Nepal\nMinistry of Health & Population\nSwarnabindu Vaccination Program')),
                ('report_footer', models.TextField(default='This is an official hospital system report. Valid without manual signature if system verified.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital/')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('child_name', models.CharField(max_length=150, verbose_name='Child Full Name')),
                ('nepali_name', models.CharField(blank=True, max_length=150, verbose_name='Child Name (Nepali)')),
                ('sex', models.CharField(choices=[('M', 'Male (पुरुष)'), ('F', 'Female (महिला)'), ('O', 'Other (अन्य)')], max_length=1)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth (AD)')),
                ('guardian_name', models.CharField(max_length=150, verbose_name='Parent / Guardian Name')),
                ('phone_number', models.CharField(db_index=True, max_length=20, verbose_name='Primary Phone Number')),
                ('secondary_phone', models.CharField(blank=True, max_length=20, verbose_name='Secondary Phone')),
                ('province', models.CharField(default='Bagmati Province', max_length=100)),
                ('district', models.CharField(default='Kavrepalanchok', max_length=100)),
                ('municipality', models.CharField(default='Panauti Municipality', max_length=100)),
                ('ward', models.CharField(default='04', max_length=20)),
                ('locality', models.CharField(max_length=150, verbose_name='Tole / Village / Address')),
                ('identification_info', models.TextField(blank=True, help_text='Citizenship/Birth Certificate number of parent')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(help_text='e.g. Swarnabindu Session 19 Ashoj 2083', max_length=200)),
                ('session_date', models.DateField(help_text='Official session date')),
                ('session_time', models.TimeField(default='09:00:00')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Open', 'Open'), ('Completed', 'Completed'), ('Postponed', 'Postponed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['session_date'],
            },
        ),
        migrations.CreateModel(
            name='SessionDateAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_date', models.DateField()),
                ('new_date', models.DateField()),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_audits', to='hospital.vaccinationsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_date', models.DateField(default=django.utils.timezone.now)),
                ('age_at_vaccination_years', models.IntegerField(default=0)),
                ('age_at_vaccination_months', models.IntegerField(default=0)),
                ('age_at_vaccination_days', models.IntegerField(default=0)),
                ('age_at_vaccination_str', models.CharField(max_length=100)),
                ('age_group', models.CharField(default='0–6 months', max_length=50)),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Height (cm)')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight (kg)')),
                ('bp_systolic', models.IntegerField(blank=True, null=True, verbose_name='Systolic BP (mmHg)')),
                ('bp_diastolic', models.IntegerField(blank=True, null=True, verbose_name='Diastolic BP (mmHg)')),
                ('temperature_c', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temperature (°C)')),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Missed', 'Missed'), ('Deferred', 'Deferred'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='hospital.patient')),
                ('next_vaccination_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_appointments', to='hospital.vaccinationsession')),
                ('vaccination_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='hospital.vaccinationsession')),
            ],
            options={
                'ordering': ['-vaccination_date'],
                'unique_together': {('patient', 'vaccination_session')},
            },
        ),
    ]
